# Generated by Django 2.2.7 on 2019-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Ans',
        ),
    ]
