# Generated by Django 2.2.7 on 2019-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_test_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
